### ISSUE TITLE
snp-pileup with -A option

### ISSUE THREAD

**Issue by jh2663** [dariober/cnv_facets#10]
Hi. I've found that some of my BAM files include some anomalous read pairs so that snp-pileup returns only empty chrXX.csv.gz files. The solution would be using '-A' flag as mentioned in here : https://github.com/mskcc/facets/issues/63

So, could you rewrite the script to include this option in your package? Thank you.

**Comment by dariober** [comment]
Thanks for reporting the issue. I'm travelling at the moment so I'll fix this in a few days by adding the `-A` option.

For the time being you can run `snp-pileup` on its own and pass the pileup file to `cnv_facets.R` (see [pileup-input](https://github.com/dariober/cnv_facets#option-2-pileup-input)). 

Alternatively, you can edit the script `cnv_facets.R` (you can find it by executing `which cnv_facets.R`) by replacing on line [276](https://github.com/dariober/cnv_facets/blob/master/bin/cnv_facets.R#L276) `'snp-pileup'` with `'snp-pileup -A'`. Note also that without properly paired reads, the parameter `--nbhd-snp` will be set to 250 instead of being set to the average insert size.

**Comment by dariober** [comment]
Hi- apologies this took so long. I uploaded to bioconda a new version of [cnv_facets](https://bioconda.github.io/recipes/cnv_facets/README.html) which implements the `--snp-count-orphans-A/`. Assuming you have conda/bioconda already installed and configured, update with:

```
conda update cnv_facets
# Or install with
conda install cnv_facets
```
