### ISSUE TITLE
v c f

### ISSUE THREAD

**Issue by xiucz** [dariober/cnv_facets#22]
Hi, @dariober 
In the R package or the old verisons, there seemed no `-vcf` parameter in the command line. I also could not find any in the paper. Can you give comments on this parameter? What does it mean or use for?

Thank you.
Xiucz

**Comment by dariober** [comment]
Hi Xiucz - The `--vcf` option specifies a VCF file of known SNPs to be used as markers to detect allele copy number changes. This file is passed to the program snp-pileup whose output goes into the functions of the original FACETS package. So the original facets package doesn't mention a VCF file because its input is already a pileup file. This should be explained in the [README](https://github.com/dariober/cnv_facets) of cnv_facets and in the [vignettes](https://github.com/mskcc/facets/blob/master/vignettes/FACETS.pdf) of facets.

Hope this helps
Dario
