### ISSUE TITLE
number of threads used is halved in script

### ISSUE THREAD

**Issue by ahwanpandey** [dariober/cnv_facets#5]
Hi again,

Sorry for bombarding your git page!

I saw that the number of threads was beinged halved in the script. Is this on purpose?

https://github.com/dariober/cnv_facets/blob/9c37014c08c36741c50f249e92993d93e95e82cc/bin/cnv_facets.R#L760

Thanks!

**Comment by dariober** [comment]
Hi- No worries, any comment, bug, question is most welcome.

Yes, the halving is intentional since each chromosome is assigned to a subprocess which in turns runs two samtools processes, bcftools and snp-pileup. So the halving prevents spawning too many processes  while at the same time making good use of the available CPUs (roughly...)
