### ISSUE TITLE
Tabular output from `cnv_facets`

### ISSUE THREAD

**Issue by Faizal-Eeman** [dariober/cnv_facets#51]
Hi @dariober,

It'd be nice to allow users to save the original output from FACETS in a tabular format rather than only having the output be in a `VCF` format. Can this be added as a new feature?

Faizal

**Comment by dariober** [comment]
Hi Faizal,

While saving the tabular output from facets should be an easy feature to add, I'm reluctant in doing so since more features mean more things to maintain and that can break later. You can convert VCF to tabular format fairly easily with [bcftools query](https://samtools.github.io/bcftools/howtos/query.html). 

I'm going to close the issue but feel free to re-open or to ask more information on how to convert vcf to tabular (biostars.org may be a better place for this).
